---
- name: Apply ELK stack namespace (if not exists)
  shell: kubectl apply -f "{{ playbook_dir }}/../../k8s/elk/namespace.yaml"
  environment:
    KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"

- name: Apply Elasticsearch deployment/statefulset and service
  shell: kubectl apply -f "{{ playbook_dir }}/../../k8s/elk/elasticsearch.yaml"
  environment:
    KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"

- name: Apply Kibana deployment and service
  shell: kubectl apply -f "{{ playbook_dir }}/../../k8s/elk/kibana.yaml"
  environment:
    KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"

- name: Apply Filebeat daemonset (or deployment)
  shell: kubectl apply -f "{{ playbook_dir }}/../../k8s/elk/filebeat.yaml"
  environment:
    KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"