apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-init-job
  namespace: health-app
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: cassandra-init
          image: cassandra:4.0
          command: ["/bin/bash", "/scripts/init.sh"]
          volumeMounts:
            - name: script-volume
              mountPath: /scripts
      volumes:
        - name: script-volume
          configMap:
            name: cassandra-init-scripts
